version: "2"

services:
  db:
    image: mysql:5.6
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
    ports:
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql
  api:
    build: .
    image: api
    container_name: api
    tty: true
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - /private/var/lib/mysql56-data:/var/lib/mysql
volumes:
  mysql-data: